export const items = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    cuisine: "Italian",
    ingredients: ["onion", "garlic", "tomato", "pepper", "bay leaves", "salt"],
    instructions: [
      "Heat some oil in the pan.",
      "Then add garlic, onion & fry it well.",
      "Then add the meat to it and mix it well.",
      "Add a dash of red pepper.",
      "Once the meat turns brown add the chopped tomatoes and the tomato puree.",
      "Now add the herbs. Mix in the bay leaves, oregano and thyme.",
      "Add salt and pepper.Add the red wine.",
    ],
    image:
      "https://images.pexels.com/photos/2092906/pexels-photo-2092906.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    name: "Chicken Stir Fry",
    cuisine: "Chinese",
    ingredients: [
      "onion",
      "garlic",
      "chicken",
      "pepper",
      "capsicum",
      "red sauce",
      "green sauce",
      "vinegar",
    ],
    instructions: [
      "In a medium size bowl, whisk together corn starch and water.",
      "Add remaining ingredients (chicken broth, soy sauce, honey, and toasted sesame oil, red pepper flakes) and whisk to combine.",
      "Set aside Add one tablespoon of olive oil to a large skillet or wok and heat over medium high heat.",
      "Add chicken (in batches if necessary) and season with salt and pepper.",
      "Cook for 3 to 5 minutes or until cooked through. Remove from skillet.",
      "Reduce heat to medium and add remaining tablespoon of oil to the skillet.",
      "Add broccoli, bell pepper, and carrots and cook, stirring occasionally, just until crisp tender.",
      "Add ginger and garlic and cook for an additional minute. Add chicken back into the skillet and stir to combine.",
      "Whisk stir fry sauce and pour over chicken and vegetables and stir gently to combine.",
      "Bring to a boil, stirring occasionally, and let boil for one minute. Serve with rice and/or chow mein if desired",
    ],
    image:
      "https://images.pexels.com/photos/9016833/pexels-photo-9016833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    name: "Chocolate Chip Cookies",
    cuisine: "American",
    ingredients: [
      "butter",
      "sugar",
      "milk",
      "flour",
      "salt",
      "baking soda",
      "vanilla",
    ],
    instructions: [
      "Take all purpose flour, salt and baking soda in a bowl and whisk it until mixed keep it aside.",
      "In another bowl, take softened butter.",
      "Beat it using a wire whisk until smooth. If using a stand mixer (with a paddle attachment) or hand mixer then skip beating only butter.",
      "Go with the next step straight away beating butter and sugar together. Add white sugar and brown sugar.",
      "Beat it until smooth and creamy. (about 2 minutes). Add milk and vanilla. Beat again until mixed.",
      "Again beat until it comes together like a dough. If doing by hand, then use a spatula and not a wire whisk.",
      "Add chocolate chips. Fold the chocolate chips into the dough.",
      "Cover the bowl with plastic wrap and chill the dough for 30 minutes in the refrigerator.",
      "Make around 1 inch size of balls from the chilled cookie dough.",
      "Place on the cookie sheet a few inches apart from each other, because they will spread as bake.",
      "Bake them for 10-12 minutes in preheated oven or until the edges look set and light brown in color and the center still looks soft.",
      "Let it cool on the sheet for 5 minutes. After that, transfer them to a cooling rack to cool them completely",
    ],
    image:
      "https://images.pexels.com/photos/14616392/pexels-photo-14616392.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
